### ISSUE TITLE
Readme missing steps

### ISSUE THREAD

**Issue by igorT** [Samsung/meminsight#6]
Just running the steps as shown leads to 
```
Running "exec:build_lifetime" (exec) task
>> /bin/sh: gradle: command not found
```

**Comment by msridhar** [comment]
Sorry about that.  There is some improved documentation for an older version of MemInsight on the `AEC` branch:

https://github.com/Samsung/meminsight/blob/AEC/README.md

You can check out the `AEC` branch to run with those instructions.  I plan to update the instructions for `master` soon.  For your particular issue, Gradle is listed as a pre-requisite, but it also needs to be in your `PATH`.

**Comment by msridhar** [comment]
Closing as hopefully this is clearer now that the documentation has been updated
